-- ROLLBACK for phase-final-revoke-authenticated.sql
BEGIN;

-- Restore authenticated table grants
GRANT INSERT, REFERENCES, SELECT, TRIGGER ON TABLE public.activity_logs TO authenticated;
GRANT INSERT, REFERENCES, SELECT, TRIGGER ON TABLE public.admin_audit_log TO authenticated;
GRANT INSERT, REFERENCES, SELECT, TRIGGER ON TABLE public.admin_impersonation_sessions TO authenticated;
GRANT ALL ON TABLE public.admin_permissions TO authenticated;
GRANT ALL ON TABLE public.admin_role_permissions TO authenticated;
GRANT ALL ON TABLE public.admin_users TO authenticated;
GRANT ALL ON TABLE public.aeps_banks TO authenticated;
GRANT ALL ON TABLE public.aeps_merchants TO authenticated;
GRANT ALL ON TABLE public.aeps_settlement_accounts TO authenticated;
GRANT ALL ON TABLE public.aeps_settlements TO authenticated;
GRANT ALL ON TABLE public.aeps_transactions TO authenticated;
GRANT ALL ON TABLE public.bbps_billers TO authenticated;
GRANT ALL ON TABLE public.bbps_charge_slabs TO authenticated;
GRANT ALL ON TABLE public.bbps_limit_slabs TO authenticated;
GRANT ALL ON TABLE public.bbps_transactions TO authenticated;
GRANT ALL ON TABLE public.card_classifications TO authenticated;
GRANT ALL ON TABLE public.commission_distribution TO authenticated;
GRANT ALL ON TABLE public.commission_ledger TO authenticated;
GRANT ALL ON TABLE public.commissions TO authenticated;
GRANT ALL ON TABLE public.disputes TO authenticated;
GRANT ALL ON TABLE public.distributors TO authenticated;
GRANT ALL ON TABLE public.export_jobs TO authenticated;
GRANT ALL ON TABLE public.finance_users TO authenticated;
GRANT ALL ON TABLE public.global_schemes TO authenticated;
GRANT ALL ON TABLE public.idempotency_keys TO authenticated;
GRANT ALL ON TABLE public.instacash_batch_items TO authenticated;
GRANT ALL ON TABLE public.instacash_batches TO authenticated;
GRANT ALL ON TABLE public.login_attempts TO authenticated;
GRANT ALL ON TABLE public.master_distributors TO authenticated;
GRANT ALL ON TABLE public.mdr_config TO authenticated;
GRANT ALL ON TABLE public.partner_api_keys TO authenticated;
GRANT ALL ON TABLE public.partner_export_limits TO authenticated;
GRANT ALL ON TABLE public.partner_merchant_links TO authenticated;
GRANT ALL ON TABLE public.partner_pos_machines TO authenticated;
GRANT ALL ON TABLE public.partner_retailers TO authenticated;
GRANT ALL ON TABLE public.partner_schemes TO authenticated;
GRANT ALL ON TABLE public.partner_t1_cron_settings TO authenticated;
GRANT ALL ON TABLE public.partner_wallet_ledger TO authenticated;
GRANT ALL ON TABLE public.partner_wallets TO authenticated;
GRANT ALL ON TABLE public.partners TO authenticated;
GRANT ALL ON TABLE public.payout_transactions TO authenticated;
GRANT ALL ON TABLE public.portal_audit_log TO authenticated;
GRANT ALL ON TABLE public.portal_settings TO authenticated;
GRANT ALL ON TABLE public.pos_assignment_history TO authenticated;
GRANT ALL ON TABLE public.pos_device_mapping TO authenticated;
GRANT ALL ON TABLE public.pos_machines TO authenticated;
GRANT ALL ON TABLE public.pos_terminals TO authenticated;
GRANT ALL ON TABLE public.pos_transactions TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_01 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_02 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_03 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_04 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_05 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_06 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_07 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_08 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_09 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_10 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_11 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2026_12 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2027_01 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2027_02 TO authenticated;
GRANT ALL ON TABLE public.pos_transactions_2027_03 TO authenticated;
GRANT ALL ON TABLE public.razorpay_pos_transactions TO authenticated;
GRANT ALL ON TABLE public.razorpay_transactions TO authenticated;
GRANT ALL ON TABLE public.recent_activities_with_location TO authenticated;
GRANT ALL ON TABLE public.retailer_schemes TO authenticated;
GRANT ALL ON TABLE public.retailers TO authenticated;
GRANT ALL ON TABLE public.reversals TO authenticated;
GRANT ALL ON TABLE public.saved_beneficiaries TO authenticated;
GRANT ALL ON TABLE public.scheme_aeps_commissions TO authenticated;
GRANT ALL ON TABLE public.scheme_aeps_settlement_charges TO authenticated;
GRANT ALL ON TABLE public.scheme_bbps_commissions TO authenticated;
GRANT ALL ON TABLE public.scheme_mappings TO authenticated;
GRANT ALL ON TABLE public.scheme_mdr_rates TO authenticated;
GRANT ALL ON TABLE public.scheme_payout_charges TO authenticated;
GRANT ALL ON TABLE public.scheme_shadval_settlement_charges TO authenticated;
GRANT ALL ON TABLE public.schemes TO authenticated;
GRANT ALL ON TABLE public.service_slabs TO authenticated;
GRANT ALL ON TABLE public.settlement_callback_logs TO authenticated;
GRANT ALL ON TABLE public.settlement_charge_slabs TO authenticated;
GRANT ALL ON TABLE public.settlements TO authenticated;
GRANT ALL ON TABLE public.shadval_settlement TO authenticated;
GRANT ALL ON TABLE public.shadval_settlement_accounts TO authenticated;
GRANT ALL ON TABLE public.sub_partners TO authenticated;
GRANT ALL ON TABLE public.subscription_commissions TO authenticated;
GRANT ALL ON TABLE public.subscription_cron_settings TO authenticated;
GRANT ALL ON TABLE public.subscription_debits TO authenticated;
GRANT ALL ON TABLE public.subscription_items TO authenticated;
GRANT ALL ON TABLE public.subscription_plans TO authenticated;
GRANT ALL ON TABLE public.subscription_product_rates TO authenticated;
GRANT ALL ON TABLE public.subscription_products TO authenticated;
GRANT ALL ON TABLE public.subscriptions TO authenticated;
GRANT ALL ON TABLE public.t1_cron_settings TO authenticated;
GRANT ALL ON TABLE public.transactions TO authenticated;
GRANT ALL ON TABLE public.user_limits TO authenticated;
GRANT ALL ON TABLE public.user_locations TO authenticated;
GRANT ALL ON TABLE public.user_sessions TO authenticated;
GRANT ALL ON TABLE public.user_totp_secrets TO authenticated;
GRANT ALL ON TABLE public.users_current_locations TO authenticated;
GRANT ALL ON TABLE public.wallet_ledger TO authenticated;
GRANT ALL ON TABLE public.wallet_transfers TO authenticated;
GRANT ALL ON TABLE public.wallets TO authenticated;

-- Restore authenticated sequence grants
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public._migrations_id_seq TO authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.card_classifications_id_seq TO authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.pos_transactions_id_seq TO authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.rate_limit_entries_id_seq TO authenticated;

-- Restore authenticated EXECUTE
GRANT EXECUTE ON FUNCTION public.add_ledger_entry(p_user_id text, p_user_role text, p_wallet_type text, p_fund_category text, p_service_type text, p_tx_type text, p_credit numeric, p_debit numeric, p_reference_id text, p_transaction_id uuid, p_status text, p_remarks text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ba_user_service_usage(p_from timestamp with time zone, p_to timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.block_mutation_activity_logs() TO authenticated;
GRANT EXECUTE ON FUNCTION public.block_mutation_admin_audit_log() TO authenticated;
GRANT EXECUTE ON FUNCTION public.block_mutation_admin_impersonation_sessions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_aeps_settlement_charge_from_scheme(p_scheme_id uuid, p_amount numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_bbps_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_category text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_commission_hierarchy(p_transaction_id uuid, p_transaction_type text, p_gross_amount numeric, p_retailer_id text, p_distributor_id text, p_master_distributor_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_payout_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_transfer_mode text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_shadval_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_transfer_mode text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_transaction_charge(p_amount numeric, p_transaction_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_next_month_partition() TO authenticated;
GRANT EXECUTE ON FUNCTION public.credit_wallet(p_retailer_id text, p_transaction_id uuid, p_amount numeric, p_description text, p_reference_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.credit_wallet_v2(p_user_id text, p_user_role text, p_wallet_type text, p_fund_category text, p_service_type text, p_amount numeric, p_credit numeric, p_transaction_id uuid, p_reference_id text, p_remarks text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.debit_wallet_bbps(p_retailer_id text, p_transaction_id uuid, p_amount numeric, p_description text, p_reference_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.debit_wallet_v2(p_user_id text, p_user_role text, p_wallet_type text, p_fund_category text, p_service_type text, p_amount numeric, p_debit numeric, p_transaction_id uuid, p_reference_id text, p_remarks text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_wallet(p_user_id text, p_user_role text, p_wallet_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_daily_export_count(p_partner_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_partner_wallet_balance(p_partner_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_wallet_balance(p_retailer_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_wallet_balance_v2(p_user_id text, p_wallet_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_transaction_commission(p_transaction_id uuid, p_transaction_type text, p_gross_amount numeric, p_retailer_id text, p_distributor_id text, p_master_distributor_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recent_failed_logins(p_email text, p_window_minutes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refund_wallet_bbps(p_retailer_id text, p_transaction_id uuid, p_amount numeric, p_description text, p_reference_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_pinelab_non_success() TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_scheme_for_user(p_user_id text, p_user_role text, p_service_type text, p_distributor_id text, p_md_id text, p_partner_entity_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_aeps_settle_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_aeps_settlement_accounts_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_aeps_settlements_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_aeps_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_partner_schemes_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_partner_t1_cron_settings_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_payout_transactions_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_pos_device_mapping_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_razorpay_pos_transactions_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_scheme_aeps_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_service_slabs_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_shadval_settlement_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_sub_partners_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_subscription_cron_settings_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_t1_cron_settings_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_updated_at_column() TO authenticated;

-- Recreate dropped open policies (USING true)
CREATE POLICY activity_logs_insert_service ON public.activity_logs FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY admin_audit_log_insert_service ON public.admin_audit_log FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Admins can create impersonation sessions" ON public.admin_impersonation_sessions FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Admins can update impersonation sessions" ON public.admin_impersonation_sessions FOR UPDATE TO public USING (true) ;
CREATE POLICY "Admins can view their impersonation sessions" ON public.admin_impersonation_sessions FOR SELECT TO public USING (true) ;
CREATE POLICY admin_impersonation_sessions_insert_service ON public.admin_impersonation_sessions FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Admins can delete admin_users" ON public.admin_users FOR DELETE TO public USING (true) ;
CREATE POLICY "Admins can insert admin_users" ON public.admin_users FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Admins can read admin_users" ON public.admin_users FOR SELECT TO public USING (true) ;
CREATE POLICY "Admins can update admin_users" ON public.admin_users FOR UPDATE TO public USING (true) ;
CREATE POLICY "Allow all" ON public.admin_users FOR ALL TO public USING (true) ;
CREATE POLICY "Anyone can view banks" ON public.aeps_banks FOR SELECT TO public USING (true) ;
CREATE POLICY aeps_settle_acct_insert ON public.aeps_settlement_accounts FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY aeps_settlements_insert ON public.aeps_settlements FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Service can insert AEPS transactions" ON public.aeps_transactions FOR INSERT TO public WITH CHECK (((auth.jwt() ->> 'role'::text) = 'service_role'::text));
CREATE POLICY "Allow all" ON public.bbps_billers FOR ALL TO public USING (true) ;
CREATE POLICY bbps_transactions_insert ON public.bbps_transactions FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Admins can manage distributors" ON public.distributors FOR ALL TO public USING (true) ;
CREATE POLICY "Anyone can read distributors" ON public.distributors FOR SELECT TO public USING (true) ;
CREATE POLICY distributors_insert ON public.distributors FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Service role full access" ON public.export_jobs FOR ALL TO public USING (true) ;
CREATE POLICY "Admins can manage master_distributors" ON public.master_distributors FOR ALL TO public USING (true) ;
CREATE POLICY "Anyone can read master_distributors" ON public.master_distributors FOR SELECT TO public USING (true) ;
CREATE POLICY master_distributors_insert ON public.master_distributors FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Service role full access" ON public.partner_api_keys FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_export_limits FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_merchant_links FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_pos_machines FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_retailers FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_schemes FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_t1_cron_settings FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_wallet_ledger FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partner_wallets FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.partners FOR ALL TO public USING (true) ;
CREATE POLICY "Retailers can insert their own payout transactions" ON public.payout_transactions FOR INSERT TO public WITH CHECK ((retailer_id = ( SELECT retailers.partner_id FROM retailers WHERE (retailers.email = auth.email()) LIMIT 1)));
CREATE POLICY "Service role can manage all payout transactions" ON public.payout_transactions FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access on portal_audit_log" ON public.portal_audit_log FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access on portal_settings" ON public.portal_settings FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on pos_assignment_history" ON public.pos_assignment_history FOR ALL TO public USING (true) ;
CREATE POLICY "Admins can manage pos_device_mapping" ON public.pos_device_mapping FOR ALL TO public USING (true) ;
CREATE POLICY "Admins can manage pos_machines" ON public.pos_machines FOR ALL TO public USING (true) ;
CREATE POLICY "Allow all" ON public.pos_machines FOR ALL TO public USING (true) ;
CREATE POLICY "Anyone can read pos_machines" ON public.pos_machines FOR SELECT TO public USING (true) ;
CREATE POLICY "Allow all" ON public.pos_terminals FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access" ON public.pos_transactions FOR ALL TO public USING (true) ;
CREATE POLICY "Admins can read razorpay_pos_transactions" ON public.razorpay_pos_transactions FOR SELECT TO public USING (true) ;
CREATE POLICY "Allow read razorpay_transactions" ON public.razorpay_transactions FOR SELECT TO public USING (true) ;
CREATE POLICY "Admins can manage retailers" ON public.retailers FOR ALL TO public USING (true) ;
CREATE POLICY "Anyone can read retailers" ON public.retailers FOR SELECT TO public USING (true) ;
CREATE POLICY retailers_insert ON public.retailers FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Retailers can insert own beneficiaries" ON public.saved_beneficiaries FOR INSERT TO public WITH CHECK ((retailer_id IN ( SELECT retailers.partner_id FROM retailers WHERE (retailers.email = (auth.jwt() ->> 'email'::text)))));
CREATE POLICY scheme_aeps_insert_policy ON public.scheme_aeps_commissions FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY aeps_settle_insert_policy ON public.scheme_aeps_settlement_charges FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY scheme_bbps_insert_policy ON public.scheme_bbps_commissions FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY scheme_mappings_insert_policy ON public.scheme_mappings FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY scheme_mappings_insert_service ON public.scheme_mappings FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY scheme_mdr_insert_policy ON public.scheme_mdr_rates FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY scheme_payout_insert_policy ON public.scheme_payout_charges FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Service role full access scheme_shadval_settlement_charges" ON public.scheme_shadval_settlement_charges FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY schemes_insert_policy ON public.schemes FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY schemes_insert_service ON public.schemes FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY "Service role full access" ON public.settlement_callback_logs FOR ALL TO public USING (true) ;
CREATE POLICY "Service role full access shadval_settlement" ON public.shadval_settlement FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access shadval_settlement_accounts" ON public.shadval_settlement_accounts FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on sub_partners" ON public.sub_partners FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all subscription_commissions" ON public.subscription_commissions FOR ALL TO public USING (true) ;
CREATE POLICY "Admin all subscription_debits" ON public.subscription_debits FOR ALL TO public USING (true) ;
CREATE POLICY "Users read own subscription_debits" ON public.subscription_debits FOR SELECT TO public USING (true) ;
CREATE POLICY "Allow all subscription_items" ON public.subscription_items FOR ALL TO public USING (true) ;
CREATE POLICY "Allow all subscription_product_rates" ON public.subscription_product_rates FOR ALL TO public USING (true) ;
CREATE POLICY "Allow all subscription_products" ON public.subscription_products FOR ALL TO public USING (true) ;
CREATE POLICY "Admin all subscriptions" ON public.subscriptions FOR ALL TO public USING (true) ;
CREATE POLICY "Users read own subscriptions" ON public.subscriptions FOR SELECT TO public USING (true) ;
CREATE POLICY wallet_ledger_insert ON public.wallet_ledger FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
CREATE POLICY wallet_transfers_insert ON public.wallet_transfers FOR INSERT TO public WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY wallets_insert ON public.wallets FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));

COMMIT;
