-- ROLLBACK for phase1-revoke-anon-and-danger-funcs.sql
-- Restores anon table/sequence/function grants and authenticated EXECUTE on danger funcs
-- Generated from live DB snapshot
BEGIN;

-- Restore anon table grants
GRANT INSERT, REFERENCES, SELECT, TRIGGER ON TABLE public.activity_logs TO anon;
GRANT INSERT, REFERENCES, SELECT, TRIGGER ON TABLE public.admin_audit_log TO anon;
GRANT INSERT, REFERENCES, SELECT, TRIGGER ON TABLE public.admin_impersonation_sessions TO anon;
GRANT ALL ON TABLE public.admin_permissions TO anon;
GRANT ALL ON TABLE public.admin_role_permissions TO anon;
GRANT ALL ON TABLE public.admin_users TO anon;
GRANT ALL ON TABLE public.aeps_banks TO anon;
GRANT ALL ON TABLE public.aeps_merchants TO anon;
GRANT ALL ON TABLE public.aeps_settlement_accounts TO anon;
GRANT ALL ON TABLE public.aeps_settlements TO anon;
GRANT ALL ON TABLE public.aeps_transactions TO anon;
GRANT ALL ON TABLE public.bbps_billers TO anon;
GRANT ALL ON TABLE public.bbps_charge_slabs TO anon;
GRANT ALL ON TABLE public.bbps_limit_slabs TO anon;
GRANT ALL ON TABLE public.bbps_transactions TO anon;
GRANT ALL ON TABLE public.card_classifications TO anon;
GRANT ALL ON TABLE public.commission_distribution TO anon;
GRANT ALL ON TABLE public.commission_ledger TO anon;
GRANT ALL ON TABLE public.commissions TO anon;
GRANT ALL ON TABLE public.disputes TO anon;
GRANT ALL ON TABLE public.distributors TO anon;
GRANT ALL ON TABLE public.export_jobs TO anon;
GRANT ALL ON TABLE public.finance_users TO anon;
GRANT ALL ON TABLE public.global_schemes TO anon;
GRANT ALL ON TABLE public.idempotency_keys TO anon;
GRANT ALL ON TABLE public.instacash_batch_items TO anon;
GRANT ALL ON TABLE public.instacash_batches TO anon;
GRANT ALL ON TABLE public.login_attempts TO anon;
GRANT ALL ON TABLE public.master_distributors TO anon;
GRANT ALL ON TABLE public.mdr_config TO anon;
GRANT ALL ON TABLE public.partner_api_keys TO anon;
GRANT ALL ON TABLE public.partner_export_limits TO anon;
GRANT ALL ON TABLE public.partner_merchant_links TO anon;
GRANT ALL ON TABLE public.partner_pos_machines TO anon;
GRANT ALL ON TABLE public.partner_retailers TO anon;
GRANT ALL ON TABLE public.partner_schemes TO anon;
GRANT ALL ON TABLE public.partner_t1_cron_settings TO anon;
GRANT ALL ON TABLE public.partner_wallet_ledger TO anon;
GRANT ALL ON TABLE public.partner_wallets TO anon;
GRANT ALL ON TABLE public.partners TO anon;
GRANT ALL ON TABLE public.payout_transactions TO anon;
GRANT ALL ON TABLE public.portal_audit_log TO anon;
GRANT ALL ON TABLE public.portal_settings TO anon;
GRANT ALL ON TABLE public.pos_assignment_history TO anon;
GRANT ALL ON TABLE public.pos_device_mapping TO anon;
GRANT ALL ON TABLE public.pos_machines TO anon;
GRANT ALL ON TABLE public.pos_terminals TO anon;
GRANT ALL ON TABLE public.pos_transactions TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_01 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_02 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_03 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_04 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_05 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_06 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_07 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_08 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_09 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_10 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_11 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2026_12 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2027_01 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2027_02 TO anon;
GRANT ALL ON TABLE public.pos_transactions_2027_03 TO anon;
GRANT ALL ON TABLE public.razorpay_pos_transactions TO anon;
GRANT ALL ON TABLE public.razorpay_transactions TO anon;
GRANT ALL ON TABLE public.recent_activities_with_location TO anon;
GRANT ALL ON TABLE public.retailer_schemes TO anon;
GRANT ALL ON TABLE public.retailers TO anon;
GRANT ALL ON TABLE public.reversals TO anon;
GRANT ALL ON TABLE public.saved_beneficiaries TO anon;
GRANT ALL ON TABLE public.scheme_aeps_commissions TO anon;
GRANT ALL ON TABLE public.scheme_aeps_settlement_charges TO anon;
GRANT ALL ON TABLE public.scheme_bbps_commissions TO anon;
GRANT ALL ON TABLE public.scheme_mappings TO anon;
GRANT ALL ON TABLE public.scheme_mdr_rates TO anon;
GRANT ALL ON TABLE public.scheme_payout_charges TO anon;
GRANT ALL ON TABLE public.scheme_shadval_settlement_charges TO anon;
GRANT ALL ON TABLE public.schemes TO anon;
GRANT ALL ON TABLE public.service_slabs TO anon;
GRANT ALL ON TABLE public.settlement_callback_logs TO anon;
GRANT ALL ON TABLE public.settlement_charge_slabs TO anon;
GRANT ALL ON TABLE public.settlements TO anon;
GRANT ALL ON TABLE public.shadval_settlement TO anon;
GRANT ALL ON TABLE public.shadval_settlement_accounts TO anon;
GRANT ALL ON TABLE public.sub_partners TO anon;
GRANT ALL ON TABLE public.subscription_commissions TO anon;
GRANT ALL ON TABLE public.subscription_cron_settings TO anon;
GRANT ALL ON TABLE public.subscription_debits TO anon;
GRANT ALL ON TABLE public.subscription_items TO anon;
GRANT ALL ON TABLE public.subscription_plans TO anon;
GRANT ALL ON TABLE public.subscription_product_rates TO anon;
GRANT ALL ON TABLE public.subscription_products TO anon;
GRANT ALL ON TABLE public.subscriptions TO anon;
GRANT ALL ON TABLE public.t1_cron_settings TO anon;
GRANT ALL ON TABLE public.transactions TO anon;
GRANT ALL ON TABLE public.user_limits TO anon;
GRANT ALL ON TABLE public.user_locations TO anon;
GRANT ALL ON TABLE public.user_sessions TO anon;
GRANT ALL ON TABLE public.user_totp_secrets TO anon;
GRANT ALL ON TABLE public.users_current_locations TO anon;
GRANT ALL ON TABLE public.wallet_ledger TO anon;
GRANT ALL ON TABLE public.wallet_transfers TO anon;
GRANT ALL ON TABLE public.wallets TO anon;

-- Restore anon sequence grants
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public._migrations_id_seq TO anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.card_classifications_id_seq TO anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.pos_transactions_id_seq TO anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.rate_limit_entries_id_seq TO anon;

-- Restore anon EXECUTE on functions that had it
GRANT EXECUTE ON FUNCTION public.add_ledger_entry(p_user_id text, p_user_role text, p_wallet_type text, p_fund_category text, p_service_type text, p_tx_type text, p_credit numeric, p_debit numeric, p_reference_id text, p_transaction_id uuid, p_status text, p_remarks text) TO anon;
GRANT EXECUTE ON FUNCTION public.assign_pos_device(p_machine_id uuid, p_assign_to text, p_assign_to_role text, p_assigned_by text, p_assigned_by_role text, p_inventory_status text, p_owner_field text, p_clear_fields text[], p_notes text, p_sync_partner_pos boolean, p_partner_machine_data jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.ba_user_service_usage(p_from timestamp with time zone, p_to timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.backfill_pos_retailer_ids() TO anon;
GRANT EXECUTE ON FUNCTION public.block_mutation_activity_logs() TO anon;
GRANT EXECUTE ON FUNCTION public.block_mutation_admin_audit_log() TO anon;
GRANT EXECUTE ON FUNCTION public.block_mutation_admin_impersonation_sessions() TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_aeps_commission_from_scheme(p_scheme_id uuid, p_amount numeric, p_transaction_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_aeps_settlement_charge_from_scheme(p_scheme_id uuid, p_amount numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_bbps_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_category text) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_commission_hierarchy(p_transaction_id uuid, p_transaction_type text, p_gross_amount numeric, p_retailer_id text, p_distributor_id text, p_master_distributor_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_payout_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_transfer_mode text) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_shadval_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_transfer_mode text) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_shadval_settlement_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_transfer_mode text) TO anon;
GRANT EXECUTE ON FUNCTION public.calculate_transaction_charge(p_amount numeric, p_transaction_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_admin_permission(p_admin_id uuid, p_department text, p_action text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_admin_permission(p_admin_id uuid, p_permission_key text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(p_key text, p_max_requests integer, p_window_ms integer) TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_sessions() TO anon;
GRANT EXECUTE ON FUNCTION public.create_next_month_partition() TO anon;
GRANT EXECUTE ON FUNCTION public.credit_partner_wallet(p_partner_id uuid, p_amount numeric, p_description text, p_reference_id text, p_transaction_type text, p_service_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.credit_wallet(p_retailer_id text, p_transaction_id uuid, p_amount numeric, p_description text, p_reference_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.credit_wallet_v2(p_user_id text, p_user_role text, p_wallet_type text, p_fund_category text, p_service_type text, p_amount numeric, p_credit numeric, p_transaction_id uuid, p_reference_id text, p_remarks text) TO anon;
GRANT EXECUTE ON FUNCTION public.debit_partner_wallet(p_partner_id uuid, p_amount numeric, p_payout_transaction_id uuid, p_description text, p_reference_id text, p_service_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.debit_wallet_bbps(p_retailer_id text, p_transaction_id uuid, p_amount numeric, p_description text, p_reference_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.debit_wallet_v2(p_user_id text, p_user_role text, p_wallet_type text, p_fund_category text, p_service_type text, p_amount numeric, p_debit numeric, p_transaction_id uuid, p_reference_id text, p_remarks text) TO anon;
GRANT EXECUTE ON FUNCTION public.ensure_partner_wallet(p_partner_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ensure_wallet(p_user_id text, p_user_role text, p_wallet_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_aeps_stats(p_user_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_daily_export_count(p_partner_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_partner_scheme(p_partner_id uuid, p_mode text, p_card_type text, p_brand_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_partner_wallet_balance(p_partner_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_paused_partner_ids() TO anon;
GRANT EXECUTE ON FUNCTION public.get_pos_stats() TO anon;
GRANT EXECUTE ON FUNCTION public.get_pos_tracking_summary(p_date_from timestamp with time zone, p_date_to timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.get_wallet_balance(p_retailer_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_wallet_balance_v2(p_user_id text, p_wallet_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.log_activity(p_user_id text, p_user_role text, p_activity_type text, p_activity_category text, p_activity_description text, p_reference_id text, p_reference_table text, p_latitude numeric, p_longitude numeric, p_geo_accuracy numeric, p_geo_source text, p_ip_address inet, p_user_agent text, p_device_info jsonb, p_request_path text, p_request_method text, p_status text, p_error_message text, p_metadata jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.process_transaction_commission(p_transaction_id uuid, p_transaction_type text, p_gross_amount numeric, p_retailer_id text, p_distributor_id text, p_master_distributor_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.recent_failed_logins(p_email text, p_window_minutes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_business_analytics() TO anon;
GRANT EXECUTE ON FUNCTION public.refund_partner_wallet(p_partner_id uuid, p_amount numeric, p_payout_transaction_id uuid, p_description text, p_reference_id text, p_service_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.refund_wallet_bbps(p_retailer_id text, p_transaction_id uuid, p_amount numeric, p_description text, p_reference_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_pinelab_non_success() TO anon;
GRANT EXECUTE ON FUNCTION public.resolve_scheme_for_user(p_user_id text, p_user_role text, p_service_type text, p_distributor_id text, p_md_id text, p_partner_entity_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.return_pos_device(p_machine_id uuid, p_returned_by text, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_distributor_tpin(p_distributor_id text, p_tpin text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_partner_tpin(p_partner_id text, p_tpin text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_partner_wallet_frozen(p_partner_id uuid, p_frozen boolean, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_retailer_tpin(p_retailer_id text, p_tpin text) TO anon;
GRANT EXECUTE ON FUNCTION public.settle_pos_txn_t1(p_txn_id uuid, p_retailer_id text, p_gross numeric, p_retailer_mdr numeric, p_retailer_fee numeric, p_retailer_net numeric, p_scheme_id text, p_scheme_type text, p_distributor_id text, p_distributor_mdr numeric, p_distributor_commission numeric, p_tid text, p_retailer_name text, p_retailer_ref text, p_commission_ref text, p_distributor_tds numeric, p_master_distributor_id text, p_md_mdr numeric, p_md_commission numeric, p_md_commission_ref text, p_md_tds numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.update_aeps_settle_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_aeps_settlement_accounts_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_aeps_settlements_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_aeps_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_partner_schemes_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_partner_t1_cron_settings_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_payout_transactions_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_pos_device_mapping_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_razorpay_pos_transactions_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_scheme_aeps_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_service_slabs_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_shadval_settlement_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_sub_partners_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_subscription_cron_settings_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_t1_cron_settings_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.update_updated_at_column() TO anon;
GRANT EXECUTE ON FUNCTION public.verify_distributor_tpin(p_distributor_id text, p_tpin text) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_partner_tpin(p_partner_id text, p_tpin text) TO anon;
GRANT EXECUTE ON FUNCTION public.verify_retailer_tpin(p_retailer_id text, p_tpin text) TO anon;

-- Restore authenticated EXECUTE on danger funcs
GRANT EXECUTE ON FUNCTION public.assign_pos_device(p_machine_id uuid, p_assign_to text, p_assign_to_role text, p_assigned_by text, p_assigned_by_role text, p_inventory_status text, p_owner_field text, p_clear_fields text[], p_notes text, p_sync_partner_pos boolean, p_partner_machine_data jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.backfill_pos_retailer_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_aeps_commission_from_scheme(p_scheme_id uuid, p_amount numeric, p_transaction_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_shadval_settlement_charge_from_scheme(p_scheme_id uuid, p_amount numeric, p_transfer_mode text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_admin_permission(p_admin_id uuid, p_department text, p_action text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_admin_permission(p_admin_id uuid, p_permission_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(p_key text, p_max_requests integer, p_window_ms integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_sessions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.credit_partner_wallet(p_partner_id uuid, p_amount numeric, p_description text, p_reference_id text, p_transaction_type text, p_service_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.debit_partner_wallet(p_partner_id uuid, p_amount numeric, p_payout_transaction_id uuid, p_description text, p_reference_id text, p_service_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_partner_wallet(p_partner_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_aeps_stats(p_user_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_partner_scheme(p_partner_id uuid, p_mode text, p_card_type text, p_brand_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_paused_partner_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pos_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pos_tracking_summary(p_date_from timestamp with time zone, p_date_to timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_activity(p_user_id text, p_user_role text, p_activity_type text, p_activity_category text, p_activity_description text, p_reference_id text, p_reference_table text, p_latitude numeric, p_longitude numeric, p_geo_accuracy numeric, p_geo_source text, p_ip_address inet, p_user_agent text, p_device_info jsonb, p_request_path text, p_request_method text, p_status text, p_error_message text, p_metadata jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_business_analytics() TO authenticated;
GRANT EXECUTE ON FUNCTION public.refund_partner_wallet(p_partner_id uuid, p_amount numeric, p_payout_transaction_id uuid, p_description text, p_reference_id text, p_service_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.return_pos_device(p_machine_id uuid, p_returned_by text, p_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_distributor_tpin(p_distributor_id text, p_tpin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_partner_tpin(p_partner_id text, p_tpin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_partner_wallet_frozen(p_partner_id uuid, p_frozen boolean, p_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_retailer_tpin(p_retailer_id text, p_tpin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.settle_pos_txn_t1(p_txn_id uuid, p_retailer_id text, p_gross numeric, p_retailer_mdr numeric, p_retailer_fee numeric, p_retailer_net numeric, p_scheme_id text, p_scheme_type text, p_distributor_id text, p_distributor_mdr numeric, p_distributor_commission numeric, p_tid text, p_retailer_name text, p_retailer_ref text, p_commission_ref text, p_distributor_tds numeric, p_master_distributor_id text, p_md_mdr numeric, p_md_commission numeric, p_md_commission_ref text, p_md_tds numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_distributor_tpin(p_distributor_id text, p_tpin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_partner_tpin(p_partner_id text, p_tpin text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_retailer_tpin(p_retailer_id text, p_tpin text) TO authenticated;

-- Note: DEFAULT PRIVILEGES alterations are left; re-run if needed:
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon;

COMMIT;
